### ISSUE TITLE
Testosterone

### ISSUE THREAD

**Issue by bigbruno** [tmiland/Presets-for-Spooky2#1]
Your testosterone is the same added in new versions of spooky2?

I have low testosterone and buyed 4 spookies to treat this and another problems

**Comment by tmiland** [comment]
Hi, 

the preset i have is molecular wight frequencies, which are for testing purposes. 

But if you download the Spooky2 software, and search the database for testosterone, there are some frequency base in there. And if you want to test my presets, just add them in the "C:\Spooky2\Preset Collections\User" folder and load them. 

Regards,
Tommy

**Comment by bigbruno** [comment]
Thank you
